# node_exporter_version is defined at the group_vars/all
node_exporter_home: /opt/node_exporter
node_exporter_user: node-exporter
node_exporter_uid: 2000
node_exporter_grp: node-exporter
node_exporter_gid: 2000
node_exporter_port: 9100

